"""
app/api/user.py
User Studio REST endpoints for regular creators.
Provides minimalist, distraction-free script generation, history, and exports.
"""

from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.api.dependencies import get_current_user, get_db
from app.api.schemas import (
    ScriptDetailResponse,
    ScriptGenerateRequest,
    ScriptSummaryResponse,
    VideoSummaryResponse,
    VideoUploadRequest,
)
from app.core.config import settings
from app.export.beat_sheet import generate_beat_sheet
from app.export.pdf import export_screenplay_to_pdf
from app.generation.parser import calculate_screenplay_metrics, parse_screenplay_elements
from app.generation.service import ScriptService
from app.ingestion.service import IngestionService
from app.models.schema import Script, Style, User, Video

router = APIRouter(prefix="/api/v1", tags=["User Studio"])


@router.get("/scripts", response_model=List[ScriptSummaryResponse])
def list_user_scripts(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    List all scripts generated by the authenticated user.
    """
    scripts = (
        db.query(Script)
        .filter_by(user_id=user.user_id)
        .order_by(Script.created_at.desc())
        .all()
    )

    summaries = []
    for s in scripts:
        metrics = calculate_screenplay_metrics(s.script_text or "")
        summaries.append(
            ScriptSummaryResponse(
                script_id=s.script_id,
                creator_id=s.style_id,
                user_id=s.user_id,
                premise=s.premise,
                status=s.status or "draft",
                rating=s.rating,
                word_count=metrics["word_count"],
                est_duration_sec=metrics["est_duration_sec"],
                created_at=s.created_at.strftime("%Y-%m-%d %H:%M") if s.created_at else "N/A",
            )
        )
    return summaries


@router.get("/scripts/{script_id}", response_model=ScriptDetailResponse)
def get_user_script(
    script_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Fetch complete screenplay for reading with syntax-highlighted teleprompter elements.
    """
    script = db.query(Script).filter_by(script_id=script_id).first()
    if not script:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Script not found")

    # Regular users can only access their own scripts (Admins can view any)
    if user.role != "admin" and script.user_id != user.user_id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied to this screenplay")

    style = db.query(Style).filter_by(style_id=script.style_id).first()
    creator_name = style.name if (style and style.name) else script.style_id
    metrics = calculate_screenplay_metrics(script.script_text or "")
    parsed = parse_screenplay_elements(script.script_text or "")

    return ScriptDetailResponse(
        script_id=script.script_id,
        creator_id=script.style_id,
        creator_name=creator_name,
        user_id=script.user_id,
        premise=script.premise,
        script_text=script.script_text,
        status=script.status or "draft",
        rating=script.rating,
        review_notes=script.review_notes or "",
        word_count=metrics["word_count"],
        est_duration_sec=metrics["est_duration_sec"],
        created_at=script.created_at.strftime("%Y-%m-%d %H:%M") if script.created_at else "N/A",
        parsed_elements=parsed,
        style_bible=style.bible_text if (style and style.bible_text) else None,
    )


@router.post("/scripts/generate", response_model=ScriptDetailResponse)
def generate_user_script(
    request: ScriptGenerateRequest,
    user: User = Depends(get_current_user),
):
    """
    Generate an original comedic screenplay based on user premise in selected creator's style.
    """
    service = ScriptService()
    try:
        script = service.generate_script(
            style_id=request.creator_id or "default_style",
            premise=request.premise,
            user_id=user.user_id,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Script generation failed: {str(exc)}",
        )

    metrics = calculate_screenplay_metrics(script.script_text or "")
    parsed = parse_screenplay_elements(script.script_text or "")

    return ScriptDetailResponse(
        script_id=script.script_id,
        creator_id=script.style_id,
        creator_name=script.style_id,
        user_id=script.user_id,
        premise=script.premise,
        script_text=script.script_text,
        status=script.status or "draft",
        rating=script.rating,
        review_notes="",
        word_count=metrics["word_count"],
        est_duration_sec=metrics["est_duration_sec"],
        created_at=script.created_at.strftime("%Y-%m-%d %H:%M") if script.created_at else "N/A",
        parsed_elements=parsed,
    )


@router.get("/scripts/{script_id}/export/pdf")
def export_script_pdf(
    script_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Generate and stream Hollywood standard screenplay PDF (Courier 12pt, industry margins).
    """
    script = db.query(Script).filter_by(script_id=script_id).first()
    if not script:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Script not found")

    if user.role != "admin" and script.user_id != user.user_id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied")

    try:
        pdf_path = export_screenplay_to_pdf(script_id)
    except Exception as exc:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc))

    return FileResponse(
        path=pdf_path,
        media_type="application/pdf",
        filename=f"{script_id}.pdf",
    )


@router.get("/scripts/{script_id}/export/beat_sheet")
def export_script_beat_sheet(
    script_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Download 4-column shooting beat sheet & shot list table (Markdown).
    """
    script = db.query(Script).filter_by(script_id=script_id).first()
    if not script:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Script not found")

    if user.role != "admin" and script.user_id != user.user_id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied")

    try:
        _ = generate_beat_sheet(script_id, export_files=True)
    except Exception as exc:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(exc))

    md_path = settings.exports_dir / f"{script_id}_beat_sheet.md"
    return FileResponse(
        path=md_path,
        media_type="text/markdown",
        filename=f"{script_id}_beat_sheet.md",
    )


@router.post("/videos/upload", response_model=VideoSummaryResponse)
def upload_video_asset(
    request: VideoUploadRequest,
    user: User = Depends(get_current_user),
):
    """
    Ingest a new video via Instagram Reel URL or file path.
    """
    service = IngestionService()
    try:
        res = service.ingest(source=request.source_url, style_id=request.creator_id)
    except Exception as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))

    return VideoSummaryResponse(
        video_id=res.video_id,
        sha256=res.sha256[:10],
        status=res.status,
        has_extraction=False,
        has_audio=bool(res.audio_uri),
        created_at="Just now",
    )
